//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCafe_v1._5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Order_Detail
    {
        public int Id { get; set; }
        public int MenuId { get; set; }
        public int OrderId { get; set; }
        [Required(ErrorMessage = "YYYY/MM/DD")]
        public System.DateTime GenerateTime { get; set; }
        [Range(0, 20, ErrorMessage = "the range is 0 to 20")]
        public int Number { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Order Order { get; set; }
    }
}
